### ISSUE TITLE
script is not working in maya 2024

### ISSUE THREAD

**Issue by talhasener** [mhdmhd/MayaSceneConverter#10]
I am getting this error.

"MayaSceneConverter-master\ConverterUI.py line 683: module 'maya.OpenMayaUI' has no attribute 'MQtUtil_findControl' "

**Comment by mhdmhd** [comment]
I don't have "Maya" 2024, but I attempted to update it. Please try it again and let me know if it works. and tell me if it works.

**Comment by talhasener** [comment]
I solved the problem several month ago, "qtCtrl = omui.MQtUtil_findControl(ctrl)" This line is not working in new python version and I changed it with "omui.MQtUtil.findControl(ctrl)" this. After that your script executed very well.

**Comment by DavidLi78** [comment]
In the 2025 version, Qt6 and PySide6 have been transitioned. It is not known whether it is a bug or a permanent upgrade. I can run it in 2025 by modifying _shiboken6, PyQt6, and PySide6 in the script, but I cannot make it compatible with previous versions at the same time.

**Comment by mhdmhd** [comment]
I have updated the script to support Maya 2025 and it is compatible with previous versions at the same time.
