### ISSUE TITLE
vraylight size to aiarealight scale

### ISSUE THREAD

**Issue by PaulOblomov** [mhdmhd/MayaSceneConverter#2]
me can't convert those two, since aiarealight doesn't have any scale parameters (only standard maya shape scaling), while vray has it (uscale/vscale). any thoughts how to convert it ? 

with redshift you don't have such a problem, since it does have scale parameters (if i correctly remember).

**Comment by mhdmhd** [comment]
If there is no corresponding attribute(close enough functionality) then sorry there is nothing to convert, it is simple as that.
Like I described the script It gives you a great head start, but obviously you have some work to do.
I think Redshift  also doesn't have (uscale/vscale).

**Comment by PaulOblomov** [comment]
sure, no problemo. just thought it converts ut all, so both light
attributes and shape attributes are handled by ur script.
