### ISSUE TITLE
Arnold to Redshift Normal Map

### ISSUE THREAD

**Issue by jseagull3d** [mhdmhd/MayaSceneConverter#3]
I'm trying to amend the rules for converting Arnold to Redshift.

Out of the box, aiNormalMap nodes fail conversion entirely, and drop their upstream textures as well. I've set up a rule to convert aiNormalMap to RedshiftBumpMap, but it still requires manual cleanup because in Arnold the selector for tangent space is a bool and in Redshift it's an enum (for heightmap/tangent/object). Can this be fixed at a deeper level?

**Comment by mhdmhd** [comment]
Although the converter helps with similar parameters and in this case is supposed to be similar, this Arnold's parameter is very uncommonly different. I am very sorry, it seems there is no easy solution for now.
