### ISSUE TITLE
Question about creating new rules using Editor

### ISSUE THREAD

**Issue by blsinhvn** [mhdmhd/MayaSceneConverter#7]
![image](https://user-images.githubusercontent.com/116340707/197139158-f806ef22-4599-4525-8e48-b05860dbf2fa.png)

First, really appreciated the work you put into this. 
I have some questions/issues to create a new rule, so basically I used the preset "mayasoftware to vray" and when it converts, the slot for specular color is connected to the reflection color in vrayMtl. And, I believe it supposed to be connected to the reflection glossiness channel which is just float value and the problem I have is I cannot make a rule with float 3 value to float value. 

any ideas or workaround for this situation? 

btw, this script is so useful kudos to you 
thanks!

**Comment by mhdmhd** [comment]
Thanks, glad you like it.
No you cannot connect two incompatible attributes, and logically that proves that they should not be converted to each other.

**Comment by blsinhvn** [comment]
alrighty thanks!
